local BASE_DUNGEONS_PRIORITY = ZO_ACTIVITY_FINDER_SORT_PRIORITY.DUNGEONS

local Constants = {}

Constants.ACTIVITY_FINDER_SORT_PRIORITY = {
    ACTIVITY_SCHEDULE = BASE_DUNGEONS_PRIORITY + 1000,
    TRIALS = BASE_DUNGEONS_PRIORITY + 50,
}

LibPanicida.Constants = Constants
